name: Dev Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Build
        run: xmake build -y

      - name: Rename executable
        shell: pwsh
        run: |
          $shortSha = $env:GITHUB_SHA.Substring(0, 7)
          $date = Get-Date -Format "yyyyMMdd"
          Move-Item build\windows\x86\release\VirtualDesktopSwitcher.exe "VirtualDesktopSwitcher-dev+${date}-${shortSha}.exe"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VirtualDesktopSwitcher-dev
          path: VirtualDesktopSwitcher-*.exe
          if-no-files-found: error
